edition = "2023";

package hdl.rpc.v1;

import "hdl/rpc/v1/common.proto";
import "hdl/rpc/v1/control.proto";
import "hdl/rpc/v1/process.proto";
import "hdl/rpc/v1/memory.proto";
import "hdl/rpc/v1/search.proto";
import "hdl/rpc/v1/call.proto";
import "hdl/rpc/v1/hook.proto";
import "hdl/rpc/v1/locate.proto";
import "hdl/rpc/v1/discover.proto";
import "hdl/rpc/v1/code.proto";
import "hdl/rpc/v1/pe.proto";
import "hdl/rpc/v1/watch.proto";
import "hdl/rpc/v1/injection.proto";

option optimize_for = LITE_RUNTIME;

service Control {
  rpc Ping(Empty) returns (PingResponse);
  rpc SetLogLevel(SetLogLevelRequest) returns (Empty);
  rpc SetLogFile(SetLogFileRequest) returns (Empty);
  rpc SetHealthVeh(SetHealthVehRequest) returns (Empty);
  rpc GetHealthVeh(Empty) returns (GetHealthVehResponse);
  rpc Shutdown(ShutdownRequest) returns (Empty);
}

service Process {
  rpc GetHealth(Empty) returns (GetHealthResponse);
  rpc EnumRegions(Empty) returns (stream EnumRegionsResponse);
  rpc EnumModules(Empty) returns (stream EnumModulesResponse);
  rpc EnumThreads(Empty) returns (stream EnumThreadsResponse);
  rpc PollEvents(PollEventsRequest) returns (stream PollEventsResponse);
  rpc Fingerprint(FingerprintRequest) returns (stream FingerprintResponse);
}

service Memory {
  rpc ReadMemory(ReadMemoryRequest) returns (ReadMemoryResponse);
  rpc WriteMemory(WriteMemoryRequest) returns (WriteMemoryResponse);
  rpc Alloc(AllocRequest) returns (AllocResponse);
  rpc Free(FreeRequest) returns (Empty);
  rpc FindCaves(FindCavesRequest) returns (stream FindCavesResponse);
  rpc AllocNear(AllocNearRequest) returns (AllocNearResponse);
  rpc ProtectMemory(ProtectMemoryRequest) returns (ProtectMemoryResponse);
  rpc FlushICache(FlushICacheRequest) returns (Empty);
}

service Search {
  rpc SearchMemory(SearchMemoryRequest) returns (stream SearchMemoryResponse);
  rpc SearchCreate(Empty) returns (SearchCreateResponse);
  rpc SearchClose(SearchCloseRequest) returns (Empty);
  rpc SearchReset(SearchResetRequest) returns (Empty);
  rpc SearchFirst(SearchFirstRequest) returns (stream SearchFirstResponse);
  rpc SearchNext(SearchNextRequest) returns (SearchNextResponse);
  rpc SearchGetHits(SearchGetHitsRequest) returns (stream SearchGetHitsResponse);
}

service Call {
  rpc ResolveExport(ResolveExportRequest) returns (ResolveExportResponse);
  rpc CallExport(CallExportRequest) returns (CallExportResponse);
  rpc Call(CallRequest) returns (CallResponse);
  rpc CallVtable(CallVtableRequest) returns (CallVtableResponse);
}

service Hook {
  rpc HookTrace(HookTraceRequest) returns (HookTraceResponse);
  rpc Hook(HookRequest) returns (HookResponse);
  rpc EnableHook(EnableHookRequest) returns (Empty);
  rpc Unhook(UnhookRequest) returns (Empty);
  rpc PollHookHits(PollHookHitsRequest) returns (stream PollHookHitsResponse);
  rpc HookImport(HookImportRequest) returns (HookImportResponse);
}

service Locate {
  rpc ResolveRip(ResolveRipRequest) returns (ResolveRipResponse);
  rpc FollowPointers(FollowPointersRequest) returns (FollowPointersResponse);
  rpc ModuleBase(ModuleBaseRequest) returns (ModuleBaseResponse);
  rpc ResolvePattern(ResolvePatternRequest) returns (ResolvePatternResponse);
  rpc FindStringXrefs(FindStringXrefsRequest) returns (FindStringXrefsResponse);
  rpc PointerScan(PointerScanRequest) returns (PointerScanResponse);
  rpc ProbeStruct(ProbeStructRequest) returns (ProbeStructResponse);
  rpc EnumFunctions(EnumFunctionsRequest) returns (stream EnumFunctionsResponse);
  rpc XrefsFrom(XrefsFromRequest) returns (stream XrefsFromResponse);
  rpc WalkVtable(WalkVtableRequest) returns (stream WalkVtableResponse);
  rpc QueryRttiName(QueryRttiNameRequest) returns (QueryRttiNameResponse);
  rpc ResolveFunction(ResolveFunctionRequest) returns (ResolveFunctionResponse);
  rpc XrefsTo(XrefsToRequest) returns (stream XrefsToResponse);
  rpc InvalidateFnIndex(InvalidateFnIndexRequest) returns (Empty);
}

service Discover {
  rpc DiscoverCreate(Empty) returns (DiscoverCreateResponse);
  rpc DiscoverClose(DiscoverCloseRequest) returns (Empty);
  rpc DiscoverAddCandidate(DiscoverAddCandidateRequest) returns (DiscoverAddCandidateResponse);
  rpc DiscoverScanValue(DiscoverScanValueRequest) returns (DiscoverScanValueResponse);
  rpc DiscoverConstraintScan(DiscoverConstraintScanRequest) returns (Empty);
  rpc DiscoverSynthesizePattern(DiscoverSynthesizePatternRequest) returns (DiscoverSynthesizePatternResponse);
  rpc DiscoverPathConsensus(DiscoverPathConsensusRequest) returns (DiscoverPathConsensusResponse);
  rpc DiscoverPathValidate(DiscoverPathValidateRequest) returns (DiscoverPathValidateResponse);
  rpc DiscoverWatch(DiscoverWatchRequest) returns (Empty);
  rpc DiscoverUnwatchAll(DiscoverUnwatchAllRequest) returns (Empty);
  rpc DiscoverActionBegin(DiscoverActionBeginRequest) returns (Empty);
  rpc DiscoverActionEnd(DiscoverActionEndRequest) returns (Empty);
  rpc DiscoverWatchRegion(DiscoverWatchRegionRequest) returns (Empty);
  rpc DiscoverGetHeat(DiscoverGetHeatRequest) returns (DiscoverGetHeatResponse);
  rpc DiscoverRankFunctions(DiscoverRankFunctionsRequest) returns (DiscoverRankFunctionsResponse);
  rpc DiscoverWatchImport(DiscoverWatchImportRequest) returns (Empty);
  rpc DiscoverResetHeat(DiscoverResetHeatRequest) returns (Empty);
  rpc DiscoverExport(DiscoverExportRequest) returns (DiscoverExportResponse);
  rpc DiscoverImport(DiscoverImportRequest) returns (Empty);
  rpc DiscoverDiffObjects(DiscoverDiffObjectsRequest) returns (DiscoverDiffObjectsResponse);
  rpc DiscoverApplyWatchHits(DiscoverApplyWatchHitsRequest) returns (Empty);
  rpc DiscoverGetEvidence(DiscoverGetEvidenceRequest) returns (DiscoverGetEvidenceResponse);
  rpc DiscoverClusterType(DiscoverClusterTypeRequest) returns (Empty);
  rpc DiscoverGetCandidates(DiscoverGetCandidatesRequest) returns (stream DiscoverGetCandidatesResponse);
}

service Code {
  rpc DisasmEnumBackends(Empty) returns (stream DisasmEnumBackendsResponse);
  rpc DisasmGetBackend(Empty) returns (DisasmGetBackendResponse);
  rpc DisasmSetBackend(DisasmSetBackendRequest) returns (Empty);
  rpc InstrLen(InstrLenRequest) returns (InstrLenResponse);
  rpc Disasm(DisasmRequest) returns (stream DisasmResponse);
  rpc BuildStub(BuildStubRequest) returns (BuildStubResponse);
  rpc PatchCreate(PatchCreateRequest) returns (PatchCreateResponse);
  rpc PatchEnable(PatchEnableRequest) returns (Empty);
  rpc PatchRemove(PatchRemoveRequest) returns (Empty);
  rpc PatchEnum(Empty) returns (stream PatchEnumResponse);
}

service Pe {
  rpc EnumSections(EnumSectionsRequest) returns (stream EnumSectionsResponse);
  rpc EnumExports(EnumExportsRequest) returns (stream EnumExportsResponse);
  rpc EnumImports(EnumImportsRequest) returns (stream EnumImportsResponse);
}

service Watch {
  rpc WatchHw(WatchHwRequest) returns (WatchHwResponse);
  rpc WatchPage(WatchPageRequest) returns (WatchPageResponse);
  rpc Unwatch(UnwatchRequest) returns (Empty);
  rpc EnumWatches(Empty) returns (stream EnumWatchesResponse);
  rpc WatchRefresh(Empty) returns (Empty);
  rpc PollWatchHits(PollWatchHitsRequest) returns (stream PollWatchHitsResponse);
}

service Injection {
  rpc InjectDll(InjectDllRequest) returns (InjectDllResponse);
  rpc UnloadDll(UnloadDllRequest) returns (UnloadDllResponse);
  rpc TrackLoadedDll(TrackLoadedDllRequest) returns (Empty);
}
