"""Pure-Python client for hdllib-ng (out-of-process inject + named-pipe IPC)."""

from .client import CallArg, CallResult, HdlClient, HookHit, ModuleInfo, RegionInfo, Session, attach
from .exceptions import HdlError, HdlStatusError
from .feature_ops import (
    BackendInfo,
    Candidate,
    CaveInfo,
    Event,
    ExportInfo,
    FieldPred,
    HealthInfo,
    HeatField,
    ImportInfo,
    Insn,
    PatchInfo,
    SectionInfo,
    StubResult,
    SynthesizedPattern,
    ThreadInfo,
    WatchInfo,
)
from .games import GameTarget, get_game, list_games, register_game
from .inject import (
    INJECT_AUTO,
    INJECT_CREATE_REMOTE_THREAD,
    InjectCandidate,
    inject_dll,
    recommend_inject,
    resolve_target,
)
from .process import find_processes
from .protocol import HDL_OK, Op, Status
from .re_ops import (
    FunctionInfo,
    PatternResult,
    PointerPath,
    StructField,
    WatchHit,
    XrefEdge,
)
from .shell import dispatch, run_python_repl, run_shell
from .strategies import (
    AccessFinder,
    AobInjector,
    CheatEntry,
    CheatTable,
    CodePatcher,
    PointerHelper,
    StructHelper,
    ValueScan,
)
from .toolbox import (
    Code,
    DebugSession,
    DiscoverSession,
    Graph,
    Health,
    Hooks,
    Job,
    Memory,
    Pe,
    Place,
    Scanner,
    SearchSession,
    Structs,
    Watches,
    open_debug_session,
)

__all__ = [
    "AccessFinder",
    "AobInjector",
    "BackendInfo",
    "CallArg",
    "CallResult",
    "Candidate",
    "CaveInfo",
    "CheatEntry",
    "CheatTable",
    "Code",
    "CodePatcher",
    "DebugSession",
    "DiscoverSession",
    "Event",
    "ExportInfo",
    "FieldPred",
    "FunctionInfo",
    "GameTarget",
    "Graph",
    "HDL_OK",
    "HdlClient",
    "HdlError",
    "HdlStatusError",
    "Health",
    "HealthInfo",
    "HeatField",
    "HookHit",
    "Hooks",
    "INJECT_AUTO",
    "INJECT_CREATE_REMOTE_THREAD",
    "ImportInfo",
    "InjectCandidate",
    "Insn",
    "Job",
    "Memory",
    "ModuleInfo",
    "Op",
    "PatchInfo",
    "PatternResult",
    "Pe",
    "Place",
    "PointerHelper",
    "PointerPath",
    "RegionInfo",
    "Scanner",
    "SearchSession",
    "SectionInfo",
    "Session",
    "Status",
    "StructField",
    "StructHelper",
    "Structs",
    "StubResult",
    "SynthesizedPattern",
    "ThreadInfo",
    "ValueScan",
    "WatchHit",
    "WatchInfo",
    "Watches",
    "XrefEdge",
    "attach",
    "dispatch",
    "find_processes",
    "get_game",
    "inject_dll",
    "list_games",
    "open_debug_session",
    "recommend_inject",
    "register_game",
    "resolve_target",
    "run_python_repl",
    "run_shell",
]

__version__ = "0.1.0"
