#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/compiler/plugin.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream.h>

#include <memory>
#include <string>

namespace {

class HdlRpcGenerator final : public google::protobuf::compiler::CodeGenerator {
  public:
    uint64_t GetSupportedFeatures() const override { return FEATURE_SUPPORTS_EDITIONS; }
    google::protobuf::Edition GetMinimumEdition() const override {
        return google::protobuf::Edition::EDITION_2023;
    }
    google::protobuf::Edition GetMaximumEdition() const override {
        return google::protobuf::Edition::EDITION_2024;
    }

    bool Generate(const google::protobuf::FileDescriptor* file, const std::string&,
                  google::protobuf::compiler::GeneratorContext* context,
                  std::string*) const override {
        if (file->service_count() == 0) {
            return true;
        }

        std::unique_ptr<google::protobuf::io::ZeroCopyOutputStream> header(
            context->Open("hdl/rpc/v1/services.rpc.hpp"));
        google::protobuf::io::Printer out(header.get(), '$');
        out.Print("#pragma once\n\n#include <cstdint>\n#include <string_view>\n\n");
        out.Print("namespace hdl::rpc {\n\nenum class Method : uint16_t {\n");
        for (int s = 0; s < file->service_count(); ++s) {
            const auto* service = file->service(s);
            for (int m = 0; m < service->method_count(); ++m) {
                out.Print("  $name$,\n", "name", service->method(m)->name());
            }
        }
        out.Print("};\n\nstruct MethodMetadata {\n"
                  "  Method method;\n  std::string_view name;\n  bool server_streaming;\n"
                  "};\n\ninline constexpr MethodMetadata kMethods[] = {\n");
        for (int s = 0; s < file->service_count(); ++s) {
            const auto* service = file->service(s);
            for (int m = 0; m < service->method_count(); ++m) {
                const auto* method = service->method(m);
                std::string path(file->package().data(), file->package().size());
                path.push_back('.');
                path.append(service->name().data(), service->name().size());
                path.push_back('/');
                path.append(method->name().data(), method->name().size());
                out.Print("  {Method::$method$, \"$path$\", $stream$},\n", "method", method->name(),
                          "path", path, "stream", method->server_streaming() ? "true" : "false");
            }
        }
        out.Print("};\n\ninline constexpr std::string_view MethodName(Method method) {\n"
                  "  for (const auto& item : kMethods) {\n"
                  "    if (item.method == method) return item.name;\n"
                  "  }\n  return {};\n}\n\n"
                  "inline constexpr bool MethodIsServerStreaming(Method method) {\n"
                  "  for (const auto& item : kMethods) {\n"
                  "    if (item.method == method) return item.server_streaming;\n"
                  "  }\n  return false;\n}\n\n"
                  "inline bool ParseMethod(std::string_view name, Method* out) {\n"
                  "  if (!out) return false;\n"
                  "  for (const auto& item : kMethods) {\n"
                  "    if (item.name == name) { *out = item.method; return true; }\n"
                  "  }\n  return false;\n}\n\n} // namespace hdl::rpc\n");

        std::unique_ptr<google::protobuf::io::ZeroCopyOutputStream> dispatch(
            context->Open("hdl/rpc/v1/services.rpc.dispatch.inc"));
        google::protobuf::io::Printer inc(dispatch.get(), '$');
        inc.Print(
            "/* Generated by hdl_rpc_codegen. Define HDL_RPC_METHOD(Name) before include. */\n");
        for (int s = 0; s < file->service_count(); ++s) {
            const auto* service = file->service(s);
            for (int m = 0; m < service->method_count(); ++m) {
                inc.Print("HDL_RPC_METHOD($name$)\n", "name", service->method(m)->name());
            }
        }
        return true;
    }
};

} // namespace

int main(int argc, char** argv) {
    HdlRpcGenerator generator;
    return google::protobuf::compiler::PluginMain(argc, argv, &generator);
}
